### PR TITLE
Continent

### PR DESCRIPTION
**Pull request by OscarStjernfeldt**
Divide quiz into continents with switch cases

### CODE REVIEW

**Review by Yuriks1 — APPROVED** [review]
Looks good!

**Review by ToniKaru — CHANGES_REQUESTED** [review]
1. Oceania and Austraila are different areas. 
2. Nothing happens when i click on Austraila. 
3. Should back button send you back to the map or to the second home screen?

**Review by ToniKaru — APPROVED** [review]
Fantastic job! 😄

**Review by Yuriks1 — COMMENTED** [review]
Looks good!

**Review by ToniKaru — APPROVED** [review]
Need to make Australia and Oceania one clickable area, instead of two, but good enough for now! :)

**Review by Yuriks1 — APPROVED** [review]
Looks good!

**Pull request merged**
