### PR TITLE
Add profile page

### PR DESCRIPTION
**Pull request by DarkendHall**

### CODE REVIEW

**Review by ToniKaru — COMMENTED** [review]
1. Check new password matches acceptable pattern, and second matches first (like on register page) and should probably warn if you don't write anything in old password field
Can probably wait:
1. Circle border to hold profile pic (so player has an idea of the size and shape of image to upload)
2. Placeholder profile pic holder is missing. 
3. Uploaded image is stretched
4. Page title "Profile" is missing
5. Center leaderboard participation checkbox

**Review by ToniKaru — DISMISSED** [review]
Please look into:
Altered Login page behavior - on a large screen the formula is narrower than previously and gets wider when its window is made narrower.

Please check if this is intended:
This commit also alters a large number of what seem to be non-related files, checking that this is intended.

**Review by Yuriks1 — APPROVED** [review]
Amazing!

**Review by ToniKaru — APPROVED** [review]
Awesome!
(Note: Added bug fix request to trello for resizing issues related to password length.)

**Pull request merged**
